name: autofix.ci  # needed to securely identify the workflow

on:
  workflow_dispatch:
  pull_request_target:
    paths: ["**.json", "**.cpp", "**.hpp", "**.h", "**.c"]

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - run: sudo apt-get install astyle
      - run: make astyle
      - run: make style-all-json-parallel RELEASE=1

      - uses: autofix-ci/action@8caa572fd27b0019a65e4c695447089c8d3138b9
        with:
          commit-message: "style(autofix.ci): format code"
